### ISSUE TITLE
'input/Flags.h' file  not found

### ISSUE THREAD

**Issue by Niemandausduisburg** [ProtonAOSP/android_frameworks_native#1]
In file included from device/nokia/NB1/camera/QCamera2/util/QCameraDisplay.cpp:37:
In file included from device/nokia/NB1/camera/QCamera2/util/QCameraDisplay.h:56:
In file included from frameworks/native/libs/gui/include/gui/DisplayEventReceiver.h:28:
frameworks/native/libs/gui/include/gui/ISurfaceComposer.h:29:10: fatal error: 'input/Flags.h' file 
not found
#include <input/Flags.h>

**Comment by kdrag0n** [comment]
Not an issue for any official device.

**Comment by Niemandausduisburg** [comment]
@kdrag0n No solution how to fix this?
